name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Unix:
    uses: ./.github/workflows/build-desktop.yml
    with:
      full_matrix: ${{ github.event_name == 'push' }}

  Windows:
    uses: ./.github/workflows/build-windows.yml

  macOS:
    uses: ./.github/workflows/build-macos.yml

  Haiku:
    uses: ./.github/workflows/build-haiku.yml

  Consoles:
    uses: ./.github/workflows/build-console.yml

  Other:
    uses: ./.github/workflows/build-other.yml

  Compilers:
    uses: ./.github/workflows/build-old-compilers.yml